#!/usr/bin/env ruby
#
#   irb.rb - intaractive ruby
#   	$Release Version: 0.9.5 $
#   	$Revision: 11708 $
#   	$Date: 2007-02-13 08:01:19 +0900 (Tue, 13 Feb 2007) $
#   	by Keiju ISHITSUKA(keiju@ruby-lang.org)
#

require "irb"

require 'rubygems'
require 'dm-core'
require 'dm-migrations'

dir = File.dirname(__FILE__)
$LOAD_PATH.unshift(dir) unless $LOAD_PATH.include? dir

%w(quote).each { |model| require "models/#{model}" }
db = "sqlite3://quotes.db}"

puts "Setting up db: #{db}"
DataMapper.setup(:default, db)
DataMapper.finalize
DataMapper.auto_upgrade!
if __FILE__ == $0
  IRB.start(__FILE__)
else
  # check -e option
  if /^-e$/ =~ $0
    IRB.start(__FILE__)
  else
    IRB.setup(__FILE__)
  end
end
